classname: pipelines.spotter_v2.pipeline.SpotterRaw

triggers:
  - .*\spot1945.zip

retriever:
  path: pipelines/spotter_v2/config/retriever.yaml

dataset:
  path: pipelines/spotter_v2/config/dataset.yaml

quality:
  path: shared/quality.yaml
storage:
  path: shared/storage.yaml
